### ISSUE TITLE
Issue executing this sample project on BrowserStack

### ISSUE THREAD

**Issue by UmangSardesai** [Behat/MinkExtension-example#11]
So I wanted to run this sample repo on BrowserStack. As suggested [here](https://github.com/Behat/MinkExtension/pull/114#issuecomment-29294929), I made the following changes in the `behat.yml` to run tests on BrowserStack:

```
default:
  extensions:
    Behat\MinkExtension\Extension:
      browserstack:
        username: "<username>"
        access_key: "<automate-key>"
        browser: iPhone
        capabilities: {"version": "", "device": "iPhone 5"}
      default_session: browserstack
      javascript_session: browserstack
```

However, I get this exception given below: 

```
[Symfony\Component\Config\Definition\Exception\InvalidConfigurationException]
  Unrecognized options "browserstack" under "behat.extensions.behat_minkextension_extension"
```

Can you please tell me where I might be going wrong?
