### ISSUE TITLE
ElementNotFoundException happening with behat3.5.0 and selenium3

### ISSUE THREAD

**Issue by pavanyogi** [Behat/MinkExtension-example#14]
Hi All,

composer.json
```json
{
    "require": {
        "behat/behat": "*",
        "behat/mink-extension":  "*",
        "behat/mink-goutte-driver":     "*",
        "behat/mink-selenium2-driver":  "dev-master",
        "facebook/webdriver": "^1.8@dev"
        
    },
    "config": {
        "bin-dir": "bin"
    }
}
```

behat.yml
```yaml
default:
    extensions:
        Behat\MinkExtension:
            sessions:
                my_session:                
                    selenium2: 
                        wd_host: "http://127.0.0.1:4444/wd/hub"
                        capabilities: {"browserName" :"chrome", "platform": "LINUX", "version": "*"  }
```
feature
```gherkin
Feature: Google Search Functionality

  Scenario: Can find search results
    Given I am on "https://www.google.com/ncr"
    When I search for "Google"
    Then I should see "Google"
```
selenium command
```bash
java -jar selenium-server-standalone-3.141.59.jar > /dev/null &
```

We are getting the following ElementNotFoundException:

```
bin/behat
Feature: Google Search Functionality

  Scenario: Can find search results            # features/googleSearch.feature:3
    Given I am on "https://www.google.com/ncr" # FeatureContext::visit()
    When I search for "Google"                 # FeatureContext::iSearchFor()
      Form field with id|name|label|value|placeholder "q" not found. (Behat\Mink\Exception\ElementNotFoundException)
    Then I should see "Google"                 # FeatureContext::assertPageContainsText()

--- Failed scenarios:

    features/googleSearch.feature:3

1 scenario (1 failed)
3 steps (1 passed, 1 failed, 1 skipped)
0m6.67s (10.20Mb)
```
Please share your input, if we are missing any required configuration.
Thanks.
