### ISSUE TITLE
change browser

### ISSUE THREAD

**Issue by gondo** [Behat/MinkExtension-example#7]
hi
how to change browser from firefox to chrome?

**Comment by gondo** [comment]
ok i got it:

``` yaml
#behat.yml
default:
    extensions:
        Behat\MinkExtension\Extension:
#change default browser
            browser_name: 'chrome'
            base_url: http://en.wikipedia.org
            goutte: ~
            selenium2:
#change browser just for selenium
              browser: 'chrome'
```
